config/routes.rb
Rails.application.routes.draw do
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :ingredients
  resources :recipes_ingredients
  
  resources :users do
    resources :recipes
  end

  get 'about' => 'static_pages#about'
  get 'opensource' => 'static_pages#opensource'
  root 'static_pages#home'
end

app/models/recipes_ingredient.rb
class RecipesIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/controllers/recipes_ingredients_controller.rb
class RecipesIngredientsController < ApplicationController
  before_action :set_recipes_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /recipes_ingredients
  # GET /recipes_ingredients.json
  def index
    @recipes_ingredients = RecipesIngredient.all
  end

  # GET /recipes_ingredients/1
  # GET /recipes_ingredients/1.json
  def show
  end

  # GET /recipes_ingredients/new
  def new
    @recipes_ingredient = RecipesIngredient.new
  end

  # GET /recipes_ingredients/1/edit
  def edit
  end

  # POST /recipes_ingredients
  # POST /recipes_ingredients.json
  def create
    @recipes_ingredient = RecipesIngredient.new(recipes_ingredient_params)

    respond_to do |format|
      if @recipes_ingredient.save
        format.html { redirect_to @recipes_ingredient, notice: 'Recipes ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @recipes_ingredient }
      else
        format.html { render :new }
        format.json { render json: @recipes_ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes_ingredients/1
  # PATCH/PUT /recipes_ingredients/1.json
  def update
    respond_to do |format|
      if @recipes_ingredient.update(recipes_ingredient_params)
        format.html { redirect_to @recipes_ingredient, notice: 'Recipes ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipes_ingredient }
      else
        format.html { render :edit }
        format.json { render json: @recipes_ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes_ingredients/1
  # DELETE /recipes_ingredients/1.json
  def destroy
    @recipes_ingredient.destroy
    respond_to do |format|
      format.html { redirect_to recipes_ingredients_url, notice: 'Recipes ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipes_ingredient
      @recipes_ingredient = RecipesIngredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipes_ingredient_params
      params.require(:recipes_ingredient).permit(:recipe_id, :ingredient_id, :quantity, :unit)
    end
end

app/helpers/recipes_ingredients_helper.rb
module RecipesIngredientsHelper
end

app/views/recipes_ingredients/_form.html.erb
<%= form_for(recipes_ingredient) do |f| %>
  <% if recipes_ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipes_ingredient.errors.count, "error") %> prohibited this recipes_ingredient from being saved:</h2>

      <ul>
      <% recipes_ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :recipe_id %>
    <%= f.number_field :recipe_id %>
  </div>

  <div class="field">
    <%= f.label :ingredient_id %>
    <%= f.number_field :ingredient_id %>
  </div>

  <div class="field">
    <%= f.label :quantity %>
    <%= f.text_field :quantity %>
  </div>

  <div class="field">
    <%= f.label :unit %>
    <%= f.text_field :unit %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes_ingredients/edit.html.erb
<h1>Editing Recipes Ingredient</h1>

<%= render 'form', recipes_ingredient: @recipes_ingredient %>

<%= link_to 'Show', @recipes_ingredient %> |
<%= link_to 'Back', recipes_ingredients_path %>

app/views/recipes_ingredients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipes Ingredients</h1>

<table>
  <thead>
    <tr>
      <th>Recipe</th>
      <th>Ingredient</th>
      <th>Quantity</th>
      <th>Unit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes_ingredients.each do |recipes_ingredient| %>
      <tr>
        <td><%= recipes_ingredient.recipe_id %></td>
        <td><%= recipes_ingredient.ingredient_id %></td>
        <td><%= recipes_ingredient.quantity %></td>
        <td><%= recipes_ingredient.unit %></td>
        <td><%= link_to 'Show', recipes_ingredient %></td>
        <td><%= link_to 'Edit', edit_recipes_ingredient_path(recipes_ingredient) %></td>
        <td><%= link_to 'Destroy', recipes_ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipes Ingredient', new_recipes_ingredient_path %>

app/views/recipes_ingredients/new.html.erb
<h1>New Recipes Ingredient</h1>

<%= render 'form', recipes_ingredient: @recipes_ingredient %>

<%= link_to 'Back', recipes_ingredients_path %>

app/views/recipes_ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Recipe:</strong>
  <%= @recipes_ingredient.recipe_id %>
</p>

<p>
  <strong>Ingredient:</strong>
  <%= @recipes_ingredient.ingredient_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @recipes_ingredient.quantity %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @recipes_ingredient.unit %>
</p>

<%= link_to 'Edit', edit_recipes_ingredient_path(@recipes_ingredient) %> |
<%= link_to 'Back', recipes_ingredients_path %>