config/routes.rb
Rails.application.routes.draw do
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :ingredients
  resources :recipes_ingredients
  
  resources :users do
    resources :recipes
  end

  get 'about' => 'static_pages#about'
  get 'opensource' => 'static_pages#opensource'
  root 'static_pages#home'
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="navbar-header">

    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
    </button> <a class="navbar-brand" href="#">Wolfie Eats</a>
  </div>

  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li class="active">
        <%= link_to 'Home', root_path %>
      </li>
      <li>
        <%= link_to 'About', about_path %>
      </li>
      <li>
        <%= link_to 'Opensource', opensource_path %>
      </li>
      <% if logged_in? %>
        <li>
          <%= link_to 'Dashboard', current_user %>
        </li>
        <li>
          <%= link_to 'Logout', logout_path, method: "delete" %>
        </li>
      <% else %>
        <li>
          <%= link_to 'Login', login_path %>
        </li>
        <li>
          <%= link_to 'Register', new_user_path %>
        </li>
      <% end %>
    </ul>
  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WolfieEats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>